feat(notification): added notification resource
skandertebo/gallerique-backend pull request #15
Opened 2024-04-27 15:53 UTC by yasminekharrat123

2024-04-30 13:29 UTC, skandertebo requested changes

2024-04-30 13:29 UTC, skandertebo commented on src/notifications/notifications.resolver.ts
> +  @Mutation(() => Notification)
Why is there a resolver that creates notifciations, the user should not create notifications on his own, on the contrary there should be a resolver that fetches the users notifications paginated and ordered by creation date

2024-05-03 11:14 UTC, skandertebo commented on src/generic/generic.resolver.ts
> +      this.BaseService = BaseService;
b miniscule pls

2024-05-03 11:14 UTC, skandertebo commented on src/generic/generic.resolver.ts
> +function capitalize(name: string) {
put this function in utils or helpers folder

2024-05-03 11:14 UTC, skandertebo commented on src/generic/generic.service.ts
> +    await this.repository.delete(id);
I prefer returning what the repository delete function returns, as it would infer more details rather than a returned true

2024-05-03 11:48 UTC, yasminekharrat123 commented on src/notifications/notifications.resolver.ts
> +  @Mutation(() => Notification)
done

2024-05-05 17:00 UTC, skandertebo approved these changes

2024-05-05 17:00 UTC, skandertebo commented on package.json
> +    "lint-staged": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix --max-warnings=0"
nope, leave lint-staged as it is

2024-05-05 17:00 UTC, skandertebo commented on src/helpers/capitalize.ts
why not an async function that takes an object and uses adapter pattern with strategy pattern for capitalization and emit to an rxjs observable after entering a mutex to have a function that ensure full capitalism in the world.
joking, fadit :(

2024-05-05 17:05 UTC, merged